Repository scania/corporate-ui-dev, pull requests merged in 2019-08, with the labels that each got.

#174 Add header link items mobile
  package.json
  public/components/c-header.js
  public/components/c-navigation.js
  public/helpers.js
  public/style/global.scss
  public/templates/headerPage.js
  src/components/content/content.tsx
  src/components/header/header.e2e.ts
  src/components/header/header.tsx
  src/components/navigation/navigation.e2e.ts
  src/components/navigation/navigation.tsx
Labels: Feature

#171 Add support for theme icons
  package.json
  public/templates/icons-page.js
  src/components/icon/icon.tsx
  src/components/theme/theme.tsx
  src/global.ts
  src/store.ts
  utils/index.js
Labels: Feature

#172 Add bootstrap preview
  public/elements/alerts.js
  public/elements/badge.js
  public/elements/breadcrumb.js
  public/elements/button-group.js
  public/elements/buttons.js
  public/elements/card.js
  public/elements/carousel.js
  public/elements/code.js
  public/elements/dropdowns.js
  public/elements/figures.js
  public/elements/forms.js
  public/elements/images.js
  public/elements/input-group.js
  public/elements/jumbotron.js
  public/elements/list-group.js
  public/elements/media-object.js
  public/elements/modal.js
  public/elements/navs.js
  public/elements/pagination.js
  public/elements/popovers.js
  public/elements/progress.js
  public/elements/spinners.js
  public/elements/tables.js
  public/elements/toasts.js
  public/elements/tooltips.js
  public/helpers.js
  public/stories.js
  public/style/global.scss
  public/utilities/borders.js
  public/utilities/close-icon.js
  public/utilities/colors.js
  public/utilities/display.js
  public/utilities/embed.js
  public/utilities/flex.js
  public/utilities/float.js
  public/utilities/image-replacement.js
  public/utilities/position.js
  public/utilities/shadows.js
  public/utilities/sizing.js
  public/utilities/text.js
  public/utilities/vertical-alignment.js
Labels: Feature

#175 Added release toggler to storybook
  gulpfile.babel.js
  package.json
  public/config.js
  public/manager-head.html
Labels: Feature

#181 Update scania theme version
  package.json
Labels: Improvement

#182 Fix parsing error in storybook static server
  public/webpack.config.js
Labels: bug
