Repository scania/corporate-ui-dev, pull requests merged in 2019-05, with the labels that each got.

#111 Update package.json
  package.json
Labels: Improvement

#112 Initial setup for unit and e2e testing
  src/components/header/header.e2e.ts
  src/components/header/header.spec.ts
  src/unittest.ts
Labels: Feature

#113 Add docs for testing
  readme.md
Labels: Improvement

#119 Add support for global styling
  public/helpers.js
  public/preview-head.html
  public/style/global.scss
  src/components/content/content.scss
  src/components/footer/footer.tsx
  src/components/global-style/global-style.scss
  src/components/global-style/global-style.tsx
  src/components/theme/theme.tsx
  src/themes/scania/c-content.scss
  src/themes/scania/c-footer.scss
  src/themes/scania/c-header.scss
  src/themes/scania/c-navigation.scss
  src/themes/scania/c-social-media.scss
  src/themes/scania/c-theme.scss
  utils/themes.js
Labels: Feature

#121 Initial test for existing components
  src/components/content/content.e2e.ts
  src/components/content/content.spec.ts
  src/components/footer/footer.e2e.ts
  src/components/footer/footer.spec.ts
  src/components/footer/footer.tsx
  src/components/header/header.e2e.ts
  src/components/navigation/navigation.e2e.ts
  src/components/navigation/navigation.spec.ts
  src/components/social-media/social-media.e2e.ts
  src/components/social-media/social-media.spec.ts
Labels: Improvement

#120 Add css variable fallback for ie
  public/preview-head.html
  src/themes/scania/c-footer.scss
  src/themes/scania/c-header.scss
  src/themes/scania/c-navigation.scss
  src/themes/scania/c-theme.scss
Labels: Feature

#128 Update readme.md
  readme.md
Labels: Improvement

#126 - Added bootstrap script
  package.json
  public/components/c-navigation.js
  public/style/global.scss
  src/components/global-style/global-style.scss
  src/components/global-style/global-style.tsx
  src/themes/scania/c-navigation.scss
Labels: Feature

#127 Add short name for c-header
  public/components/c-header.js
  src/components/header/header.scss
  src/components/header/header.tsx
  src/themes/scania/c-header.scss
Labels: Improvement

#133 Improvement/add examples in storybook
  public/components/c-navigation.js
  public/helpers.js
  public/style/global.scss
  public/templates/examples.js
  public/templates/getting-started.html
Labels: Improvement

#125 Bug FIX - border right
  src/themes/scania/c-navigation.scss
Labels: bug

#135 Add quick start instruction in the readme
  readme.md
Labels: Improvement

#136 Add contributing guidelines
  CONTRIBUTING.md
Labels: Feature

#137 Fixed issue with contribution links
  readme.md
Labels: Improvement

#132 Footer mobile mode
  src/components/footer/footer.scss
  src/components/footer/footer.tsx
  src/components/social-media/social-media.scss
  src/themes/scania/c-footer.scss
Labels: Improvement

#134 Add correct information in package.json
  package.json
Labels: Improvement

#139 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement-request.md
Labels: Improvement

#140 Changed version number 4.0.0-alpha.2
  package.json
Labels: Improvement

#141 Update readme
  readme.md
Labels: Improvement
