Repository scania/corporate-ui-dev, pull requests merged in 2019-02, with the labels that each got.

#12 Refined theme solution
  .gitignore
  __mocks__/@stencil/state-tunnel.tsx
  build.js
  package.json
  src/components/cui-footer/cui-footer.tsx
  src/components/cui-header/cui-header.tsx
  src/components/cui-theme/cui-theme.tsx
  src/themes/corporate/cui-theme.css
  src/themes/man/cui-theme.css
  src/themes/scania/cui-theme.css
Labels: enhancement

#13 Add template section to storybook
  .storybook/manager-head.html
  .storybook/preview-head.html
  .storybook/webpack.config.js
  package.json
  src/components.json
  src/components.scss
  src/components/categories.json
  src/components/data.json
  src/templates/categories.json
  src/templates/data.json
  src/templates/main-page.html
  stories/components.js
  stories/templates.js
Labels: enhancement

#23 Slack join badge added
  readme.md
Labels: enhancement

#21 Updated readme link for slack
  readme.md
Labels: enhancement

#22 Add documentation to stories
  .gitignore
  .storybook/addons.js
  .storybook/config.js
  .storybook/helpers.js
  .storybook/kinds/components.js
  .storybook/kinds/info.js
  .storybook/kinds/templates.js
  .storybook/middleware.js
  .storybook/stories/c-header.html
  .storybook/webpack.config.js
  data/categories.json
  data/components.json
  data/contents.json
  data/stats.json
  data/templates.json
  package.json
  projects/angular/src/app/app.component.html
  projects/angular/src/app/app.component.ts
  projects/react/src/App.js
  src/components/header/header.tsx
  src/index.html
  src/templates/categories.json
  src/templates/data.json
  stencil.config.ts
  stories/components.js
  stories/templates.js
  tslint.json
Labels: enhancement

#24 Added component stats info and slack link
  .gitignore
  .storybook/addons.js
  .storybook/helpers.js
  .storybook/kinds/components.js
  .storybook/kinds/info.js
  .storybook/middleware.js
  .storybook/webpack.config.js
  projects/angular/src/app/app.component.ts
  projects/react/src/App.js
  readme.md
  src/components/header/header.tsx
  stencil.config.ts
Labels: enhancement

#29 Add watch for themes
  build.js
  package.json
  stencil.config.ts
Labels: enhancement

#25 Improved header styling
  .storybook/manager-head.html
  .storybook/preview-head.html
  build.js
  src/components.scss
  src/components/header/header.scss
  src/components/header/header.tsx
  src/components/theme/theme.scss
  src/themes/scania/header.css
  src/themes/scania/header.scss
Labels: enhancement

#15 Fixed navigation component
  src/components/navigation/navigation.tsx
  src/components/router-navigation/router-navigation.e2e.ts
  src/components/router-navigation/router-navigation.scss
  src/components/router-navigation/router-navigation.spec.ts
  src/components/router-navigation/router-navigation.tsx
  src/index.html
  src/templates/main-page.html
Labels: enhancement

#30 Updated bootstrap version to 4.3.1
  package.json
Labels: enhancement

#33 Footer component restructure
  .storybook/kinds/components.js
  .storybook/style/components.scss
  src/components.scss
  src/components/column/column.scss
  src/components/footer/footer.scss
  src/components/footer/footer.tsx
  src/components/header/header.scss
  src/themes/scania/footer.css
  src/themes/scania/footer.scss
  src/themes/scania/header.scss
Labels: enhancement

#40 Improved navigation component
  src/components/navigation/navigation.scss
  src/components/navigation/navigation.tsx
  src/themes/scania/navigation.scss
Labels: enhancement

#41 Improved header component
  src/components/header/header.scss
  src/components/header/header.tsx
  src/themes/scania/header.scss
Labels: enhancement

#42 Fixes a lot of small things
  .storybook/kinds/templates.js
  build.js
  src/components/container/container.scss
  src/components/footer/footer.tsx
  src/components/row/row.scss
  src/templates/main-page.html
Labels: enhancement

#47 Fix for component style not working in Storybook
  .storybook/config.js
  .storybook/helpers.js
  .storybook/kinds/components.js
  .storybook/middleware.js
  .storybook/preview-head.html
  projects/angular/src/app/app.component.ts
  projects/react/src/App.js
  src/components/footer/footer.tsx
  src/components/header/header.tsx
  src/components/navigation/navigation.tsx
  src/components/theme/theme.tsx
  src/store/index.ts
Labels: bug

#49 pull-request template added
  PULL_REQUEST_TEMPLATE.md
Labels: Feature

#50 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement-request.md
Labels: Feature
