Repository scania/corporate-ui-dev, pull requests merged in 2019-04, with the labels that each got.

#87 storybook fix for IE11
  gulpfile.babel.js
  package.json
Labels: bug

#88 Add documentation for header, footer, content, navigation, theme
  public/components/c-content.js
  public/components/c-footer.js
  public/components/c-header.js
  public/components/c-navigation.js
  public/components/c-theme.js
  public/helpers.js
  src/components/content/content.tsx
  src/components/footer/footer.tsx
  src/components/header/header.tsx
  src/components/navigation/navigation.tsx
  src/components/theme/theme.tsx
Labels: Improvement

#90 Improvement/change tslint to eslint
  .editorconfig
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierrc
  package.json
  public/components/c-content.js
  public/components/c-footer.js
  public/components/c-header.js
  public/components/c-navigation.js
  public/components/c-theme.js
  public/config.js
  public/helpers.js
  public/middleware.js
  public/stories.js
  public/templates/icons-page.js
  public/templates/main-page.js
  public/webpack.config.js
  src/components/card/card.tsx
  src/components/code-sample/code-sample.tsx
  src/components/column/column.tsx
  src/components/container/container.tsx
  src/components/content/content.tsx
  src/components/field/field.tsx
  src/components/footer/footer.e2e.ts
  src/components/footer/footer.tsx
  src/components/header/header.tsx
  src/components/hello-world/hello-word.spec.ts
  src/components/hello-world/hello-world.e2e.ts
  src/components/hello-world/hello-world.tsx
  src/components/icon/icon.tsx
  src/components/icon/icons.ts
  src/components/list/list.tsx
  src/components/navigation/navigation.tsx
  src/components/router-navigation/router-navigation.tsx
  src/components/row/row.tsx
  src/components/social-media/social-media.tsx
  src/components/theme/theme.tsx
  src/components/user-repos/user-repos.tsx
  src/store.ts
  tslint.json
Labels: Improvement

#92 Add missing files to the dist folder
  gulpfile.babel.js
  utils/define.js
Labels: Improvement

#91 Travis deploy for s3
  .travis.yml
Labels: Feature

#94 Create sub navigation
  public/components/c-header.js
  public/components/c-navigation.js
  src/components/code-sample/code-sample.tsx
  src/components/footer/footer.tsx
  src/components/header/header.tsx
  src/components/navigation/navigation.tsx
  src/store.ts
  src/themes/scania/c-navigation.scss
Labels: Feature

#97 Changed dynamic dependencies to static
  package.json
  tsconfig.json
Labels: Improvement

#96 Sub navigation mobile pattern
  public/components/c-navigation.js
  src/components/code-sample/code-sample.tsx
  src/components/navigation/navigation.scss
  src/components/navigation/navigation.tsx
  src/store.ts
  src/themes/scania/c-navigation.scss
Labels: Feature

#99 Changed linting scope
  .eslintignore
  .eslintrc.js
  .gitignore
  gulpfile.babel.js
  package.json
  stencil.config.ts
  tsconfig.json
  utils/define.js
  utils/storybook_template.js
  utils/themes.js
Labels: Improvement

#103 Added corporate version to the rendered dom
  src/components/theme/theme.tsx
Labels: Feature

#100 Storybook static page
  .travis.yml
  gulpfile.babel.js
  package.json
Labels: Feature

#98 Add polyfill for ie
  .eslintignore
  .eslintrc.js
  package.json
  public/components/c-navigation.js
  src/components/content/content.tsx
  src/components/footer/footer.tsx
  src/components/header/header.tsx
  src/components/navigation/navigation.scss
  src/components/navigation/navigation.tsx
  src/components/social-media/social-media.tsx
  src/themes/scania/c-footer.scss
  src/themes/scania/c-navigation.scss
  tsconfig.json
  utils/themes.js
Labels: Feature

#104 Code sample polyfill for IE
  public/preview-head.html
  src/components/code-sample/code-sample.scss
  src/components/code-sample/code-sample.tsx
Labels: Improvement

#110 Require cause error when corporate-ui.js imported inside a script
  src/components/theme/theme.tsx
Labels: bug
