Repository scania/corporate-ui-dev, pull requests merged in 2019-03, with the labels that each got.

#58 removed stats.json for ignore purpose
  data/stats.json
Labels: Improvement

#60 Update pull-request template file
  PULL_REQUEST_TEMPLATE.md
Labels: Improvement

#46 Import component in component
  .storybook/config.js
  src/helpers.js
  stencil.config.ts
Labels: Feature

#51 Added deploy process for aws s3
  .travis.yml
Labels: Feature

#57 feature - Hello-world component
  data/categories.json
  data/components.json
  src/components/hello-world/hello-word.spec.ts
  src/components/hello-world/hello-world.e2e.ts
  src/components/hello-world/hello-world.scss
  src/components/hello-world/hello-world.tsx
Labels: Feature

#59 Add a project task handler
  .gitignore
  .storybook/webpack.config.js
  gulpfile.babel.js
  package.json
  src/components/card/card.e2e.ts
  src/components/card/card.spec.ts
  src/components/column/column.e2e.ts
  src/components/column/column.spec.ts
  src/components/container/container.e2e.ts
  src/components/container/container.spec.ts
  src/components/content/content.e2e.ts
  src/components/content/content.spec.ts
  src/components/field/field.e2e.ts
  src/components/field/field.spec.ts
  src/components/footer/footer.e2e.ts
  src/components/footer/footer.tsx
  src/components/header/header.e2e.ts
  src/components/header/header.spec.ts
  src/components/header/header.tsx
  src/components/icon/icon.e2e.ts
  src/components/icon/icon.spec.ts
  src/components/list/list.e2e.ts
  src/components/list/list.spec.ts
  src/components/navigation/navigation.e2e.ts
  src/components/navigation/navigation.spec.ts
  src/components/navigation/navigation.tsx
  src/components/router-navigation/router-navigation.e2e.ts
  src/components/router-navigation/router-navigation.spec.ts
  src/components/row/row.e2e.ts
  src/components/row/row.spec.ts
  src/components/theme/theme.e2e.ts
  src/components/theme/theme.spec.ts
  src/components/theme/theme.tsx
  src/components/user-repos/user-repos.e2e.ts
  src/components/user-repos/user-repos.spec.ts
  src/global.ts
  src/index.html
  src/themes.js
  src/themes/corporate/footer.css
  src/themes/corporate/header.css
  src/themes/corporate/theme.css
  stencil.config.ts
  themes/man/footer.css
  themes/man/header.css
  themes/man/theme.css
  themes/scania/footer.scss
  themes/scania/header.scss
  themes/scania/navigation.scss
  themes/scania/theme.css
Labels: Feature

#69 Top items doesn't display
  src/components/header/header.tsx
Labels: bug

#72 Improve storybook design and ux
  .storybook/config.js
  .storybook/helpers.js
  .storybook/kinds/info.js
  .storybook/manager-head.html
  .storybook/stories/c-footer.html
  .storybook/stories/c-header.html
  .storybook/style/global.scss
  .storybook/webpack.config.js
  data/contents.json
  src/components/theme/theme.scss
  themes/scania/footer.scss
  themes/scania/navigation.scss
Labels: Improvement

#73 Add code example to storybook
  .storybook/kinds/components.js
  .storybook/preview-head.html
  package.json
  src/components/footer/footer.tsx
  src/components/header/header.tsx
  themes/scania/theme.css
  themes/scania/theme.scss
Labels: Feature

#74 Create a code sample component
  src/components/code-sample/code-sample.scss
  src/components/code-sample/code-sample.tsx
Labels: Feature

#75 Add slot support for components
  src/components/card/card.scss
  src/components/card/card.tsx
  src/components/content/content.tsx
  src/components/footer/footer.tsx
  src/components/header/header.scss
  src/components/header/header.tsx
  src/components/hello-world/hello-world.scss
  src/components/hello-world/hello-world.tsx
  src/components/navigation/navigation.tsx
  src/components/router-navigation/router-navigation.tsx
  src/components/theme/theme.scss
  src/components/theme/theme.tsx
  src/global.ts
  src/helpers.js
  src/themes.js
  themes/man/c-footer.css
  themes/man/c-header.css
  themes/man/c-theme.css
  themes/scania/c-card.scss
  themes/scania/c-content.scss
  themes/scania/c-footer.scss
  themes/scania/c-header.scss
  themes/scania/c-navigation.scss
  themes/scania/c-theme.scss
  themes/scania/footer.scss
  themes/scania/navigation.scss
Labels: Feature

#76 Storybook restructure and improvement
  .storybook/addons.js
  .storybook/components/c-footer.js
  .storybook/components/c-header.js
  .storybook/config.js
  .storybook/helpers.js
  .storybook/kinds/components.js
  .storybook/kinds/info.js
  .storybook/kinds/templates.js
  .storybook/manager-head.html
  .storybook/preview-head.html
  .storybook/stories.js
  .storybook/stories/c-footer.html
  .storybook/stories/c-header.html
  .storybook/stories/c-icon.html
  .storybook/style/components.scss
  .storybook/style/global.scss
  .storybook/templates/getting-started.html
  .storybook/templates/icons-page.js
  .storybook/templates/main-page.js
  data/categories.json
  data/components.json
  data/contents.json
  data/templates.json
  src/components/icon/icon.tsx
  src/templates/getting-started.html
  src/templates/icons-page.html
  src/templates/main-page.html
  stencil.config.ts
Labels: Improvement

#78 Add support for dynamic attributes
  .storybook/components/c-footer.js
  .storybook/components/c-header.js
  .storybook/stories.js
  package.json
  src/components/footer/footer.tsx
  src/components/header/header.tsx
  src/components/navigation/navigation.tsx
  stencil.config.ts
Labels: Feature

#79 Add global styling for html and body
  .storybook/style/global.scss
  .storybook/templates/main-page.js
  src/components/navigation/navigation.scss
  themes/scania/c-footer.scss
  themes/scania/c-header.scss
  themes/scania/c-navigation.scss
  themes/scania/c-theme.scss
Labels: Improvement

#83 Add custom footer text
  .storybook/components/c-footer.js
  src/components/footer/footer.tsx
Labels: Feature

#82 Added social media component
  .storybook/components/c-footer.js
  .storybook/components/c-header.js
  src/components/footer/footer.tsx
  src/components/header/header.tsx
  src/components/icon/icon.scss
  src/components/icon/icons.ts
  src/components/navigation/navigation.scss
  src/components/navigation/navigation.tsx
  src/components/social-media/social-media.scss
  src/components/social-media/social-media.tsx
  themes/scania/c-footer.scss
  themes/scania/c-navigation.scss
  themes/scania/c-social-media.scss
Labels: Feature

#84 Added navigation orientation option
  .storybook/components/c-navigation.js
  src/components/navigation/navigation.scss
  src/components/navigation/navigation.tsx
Labels: Feature

#85 Fix storybook server and folder structure
  .gitignore
  .storybook/webpack.config.js
  gulpfile.babel.js
  package.json
  public/addons.js
  public/components/c-footer.js
  public/components/c-header.js
  public/components/c-navigation.js
  public/config.js
  public/helpers.js
  public/manager-head.html
  public/middleware.js
  public/preview-head.html
  public/stories.js
  public/style/components.scss
  public/style/global.scss
  public/templates/getting-started.html
  public/templates/icons-page.js
  public/templates/main-page.js
  public/webpack.config.js
  src/components/card/card.tsx
  src/components/content/content.tsx
  src/components/footer/footer.tsx
  src/components/header/header.tsx
  src/components/navigation/navigation.tsx
  src/components/social-media/social-media.tsx
  src/components/theme/theme.tsx
  src/helpers.js
  src/store.ts
  src/themes/man/c-footer.css
  src/themes/man/c-header.css
  src/themes/man/c-theme.css
  src/themes/scania/c-card.scss
  src/themes/scania/c-content.scss
  src/themes/scania/c-footer.scss
  src/themes/scania/c-header.scss
  src/themes/scania/c-navigation.scss
  src/themes/scania/c-social-media.scss
  src/themes/scania/c-theme.scss
  stencil.config.ts
  utils/define.js
  utils/storybook_template.js
  utils/themes.js
Labels: Improvement
