Repository scania/corporate-ui-dev, pull requests merged in 2019-07, with the labels that each got.

#151 Global colors and theme setter in components
  package.json
  public/templates/colors.js
  src/components/card/card.tsx
  src/components/content/content.tsx
  src/components/footer/footer.tsx
  src/components/global-style/global-style.scss
  src/components/global-style/global-style.tsx
  src/components/header/header.tsx
  src/components/navigation/navigation.tsx
  src/components/social-media/social-media.tsx
  src/components/theme/theme.tsx
Labels: Feature

#146 Add sticky navigation
  package.json
  public/components/c-header.js
  public/templates/main-page.js
  src/components/footer/footer.scss
  src/components/header/header.tsx
Labels: Improvement

#155 Refactored icon solution
  package.json
  public/templates/icons-page.js
  src/components/icon/icon.scss
  src/components/icon/icon.tsx
  src/components/icon/icons.ts
Labels: Improvement

#157 Update version number to alpha 3
  package.json
Labels: Improvement

#158 Bumped version to the fixed theme
  package.json
Labels: bug

#159 Improvement/refactor footer social item setup
  package.json
  public/components/c-footer.js
  src/components/footer/footer.scss
  src/components/footer/footer.tsx
  src/components/icon/icon.scss
  src/components/social-media/social-media.e2e.ts
  src/components/social-media/social-media.scss
  src/components/social-media/social-media.spec.ts
  src/components/social-media/social-media.tsx
Labels: Improvement

#161 Loading of libs should be dynamic
  src/components/global-style/global-style.tsx
Labels: Feature

#162 Update with latest theme version for storybook
  package.json
Labels: bug
